# Generated by Django 2.1.7 on 2019-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pong', models.BooleanField()),
                ('database', models.BooleanField()),
            ],
        ),
    ]
